asset_path: /home/fwu91/Documents/DexManip/IsaacLab-Imitation/source/isaaclab_imitation/isaaclab_imitation/assets/sharpa_wave/urdfs/sharpawave/left_sharpa_wave.urdf
usd_dir: /home/fwu91/Documents/DexManip/IsaacLab-Imitation/source/isaaclab_imitation/isaaclab_imitation/assets/sharpa_wave/usd
usd_file_name: left_sharpa_wave/left_sharpa_wave.usda
force_usd_conversion: true
make_instanceable: true
fix_base: false
root_link_name: null
link_density: 0.0
merge_fixed_joints: true
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness: 0
    damping: 0
collision_from_visuals: false
collision_type: Convex Hull
self_collision: false
replace_cylinders_with_capsules: false
merge_mesh: false
ros_package_paths: []
robot_type: Default
run_asset_transformer: true
run_multi_physics_conversion: true
debug_mode: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
spawn_path: null
mass_props: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: false
  linear_damping: 0.01
  angular_damping: 0.01
  max_linear_velocity: 1000.0
  max_angular_velocity: 3666.9298888372687
  max_depenetration_velocity: 1.0
  max_contact_impulse: 1000.0
  enable_gyroscopic_forces: false
  retain_accelerations: false
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
  _usd_applied_schema: PhysxRigidBodyAPI
  _usd_field_exceptions:
    PhysxRigidBodyAPI: !!python/tuple
    - physxRigidBody
    - - disable_gravity
  _usd_namespace: physxRigidBody
collision_props: null
activate_contact_sensors: true
scale: null
articulation_props:
  articulation_enabled: null
  fix_root_link: null
  enabled_self_collisions: true
  solver_position_iteration_count: 8
  solver_velocity_iteration_count: 0
  sleep_threshold: 0.005
  stabilization_threshold: 0.0005
  _usd_applied_schema: PhysxArticulationAPI
  _usd_field_exceptions:
    PhysxArticulationAPI: !!python/tuple
    - physxArticulation
    - - articulation_enabled
  _usd_namespace: physxArticulation
fixed_tendons_props: null
spatial_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
physics_material_path: material
physics_material: null
##
# Generated by UrdfConverter on 2026-09-06 at 21:20:40.
##
