#!/usr/bin/env python3
"""Write a single-link rigid URDF for one object mesh.

The Sharpa v1 reference contract accepts exactly one rigid body, so an
articulated source object (the ARCTIC box is a hinged bottom plus top) has to
be reduced to a documented rigid proxy before it can drive a simulation. This
tool writes the proxy asset for one part mesh.

It follows the released ``generate_rigid_urdfs.py`` convention: one link named
``object``, the same mesh for visual and collision, mass 0.3 kg, and a
diagonal inertia of 1e-3. Those values are placeholders in the released
pipeline too; the reference's own ``ScenePhysics`` is what the environment
applies at run time.

Example:

    pixi run python scripts/data/make_rigid_object_urdf.py \\
        --mesh .../object_assets/meshes/arctic/box/bottom_watertight_tiny.obj \\
        --output data/dexmanip/sharpa/assets/arctic_box_bottom/object.urdf
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path

URDF_TEMPLATE = """<?xml version="1.0"?>
<!-- Rigid proxy generated by scripts/data/make_rigid_object_urdf.py. -->
<robot name="{name}">
  <link name="object">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="{mass}"/>
      <inertia ixx="{inertia}" ixy="0" ixz="0" iyy="{inertia}" iyz="0" izz="{inertia}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><mesh filename="{mesh}" scale="{scale} {scale} {scale}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><mesh filename="{mesh}" scale="{scale} {scale} {scale}"/></geometry>
    </collision>
  </link>
</robot>
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mesh", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--name", default=None, help="URDF robot name.")
    parser.add_argument("--mass", type=float, default=0.3)
    parser.add_argument("--inertia", type=float, default=1.0e-3)
    parser.add_argument(
        "--scale",
        type=float,
        default=1.0,
        help="Mesh vertex scale; 1.0 when the source mesh is already in meters.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    mesh = args.mesh.expanduser().resolve()
    if not mesh.is_file():
        raise SystemExit(f"Object mesh does not exist: {mesh}")
    output = args.output.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    # Keep the mesh next to the URDF so the asset is self-contained: the
    # reference contract hashes the URDF and resolves its mesh URIs relative
    # to it.
    local_mesh = output.parent / mesh.name
    if not local_mesh.exists() or local_mesh.stat().st_mtime < mesh.stat().st_mtime:
        shutil.copy2(mesh, local_mesh)

    output.write_text(
        URDF_TEMPLATE.format(
            name=args.name or output.stem,
            mass=args.mass,
            inertia=args.inertia,
            mesh=mesh.name,
            scale=args.scale,
        ),
        encoding="utf-8",
    )
    print(f"wrote {output} (mesh {local_mesh.name})")
    try:
        import trimesh

        loaded = trimesh.load(local_mesh, force="mesh")
        extents = loaded.extents * args.scale
        radius = float(
            max(
                (loaded.vertices - loaded.vertices.mean(axis=0)).__abs__().max(),
                0.0,
            )
            * args.scale
        )
        print(
            f"  extents (m): {extents.round(4).tolist()}  "
            f"max vertex radius (m): {radius:.4f}"
        )
    except ImportError:  # pragma: no cover - trimesh is optional here
        pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
