#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export MANIFEST_PATH="${MANIFEST_PATH:-data/unitree/manifests/g1_unitree_dance102_manifest.json}"
export DATASET_PATH="${DATASET_PATH:-data/unitree/g1_dance102_hl_diffsr}"
export TRAJECTORY_NAME="${TRAJECTORY_NAME:-dance102}"
export TRAJECTORY_SOURCE="${TRAJECTORY_SOURCE:-data/unitree/npz/g1/G1_Take_102.bvh_60hz.npz}"

export PLANNER_TYPE="${PLANNER_TYPE:-dit_diffusion}"
export PLANNER_DIFFUSION_TRAIN_TIMESTEPS="${PLANNER_DIFFUSION_TRAIN_TIMESTEPS:-100}"
export PLANNER_DIFFUSION_STEPS="${PLANNER_DIFFUSION_STEPS:-16}"
export PLANNER_DIFFUSION_TIME_DIM="${PLANNER_DIFFUSION_TIME_DIM:-64}"
export PLANNER_DIFFUSION_BETA_SCHEDULE="${PLANNER_DIFFUSION_BETA_SCHEDULE:-squaredcos_cap_v2}"
export PLANNER_DIFFUSION_SCHEDULER="${PLANNER_DIFFUSION_SCHEDULER:-ddim}"
export PLANNER_DIFFUSION_DDIM_ETA="${PLANNER_DIFFUSION_DDIM_ETA:-0.0}"
export PLANNER_EVAL_DIFFUSION_NOISE_STD="${PLANNER_EVAL_DIFFUSION_NOISE_STD:-0.0}"

export PLANNER_DIT_MODEL_DIM="${PLANNER_DIT_MODEL_DIM:-176}"
export PLANNER_DIT_NUM_LAYERS="${PLANNER_DIT_NUM_LAYERS:-4}"
export PLANNER_DIT_NUM_HEADS="${PLANNER_DIT_NUM_HEADS:-8}"
export PLANNER_DIT_FEEDFORWARD_DIM="${PLANNER_DIT_FEEDFORWARD_DIM:-704}"
export PLANNER_DIT_PATCH_DIM="${PLANNER_DIT_PATCH_DIM:-16}"
export PLANNER_DIT_NUM_STATE_TOKENS="${PLANNER_DIT_NUM_STATE_TOKENS:-4}"
export PLANNER_DIT_DROPOUT="${PLANNER_DIT_DROPOUT:-0.0}"

RUN_STAMP="$(date +%Y%m%d_%H%M%S)"
export RUN_ID="${RUN_ID:-${RUN_STAMP}_dance102_h${HORIZON_STEPS:-10}_hist$(( ${STATE_HISTORY_STEPS:-9} + 1 ))_dit_diffusion_m3}"
export RUN_ROOT="${RUN_ROOT:-logs/dance102_dit_latent_m3/${RUN_ID}}"

exec "${SCRIPT_DIR}/run_lafan1_no_language_pipeline.sh" "$@"
